owner: leverup-xyz
repo: status-pages

sites:
  - name: LeverUp Service
    url: https://service.leverup.xyz/sys/health
  - name: LeverUp OneClick service
    url: https://oneclick-01-keeper.leverup.xyz/sys/health
  - name: Keeper Balance
    url: https://leverup-status-pages.vercel.app/api/check-balance
  - name: Service Health Extended
    url: http://[2a02:4780:75:b01b::1]:8888/health
    headers:
      - "X-Monitor-Token: $GH_PAT"

status-website:
  cname: https://leverup-xyz.github.io
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Twitter
      href: https://x.com/LeverUp_xyz
